// <auto-generated />
using System;
using CityCab.Rider.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CityCab.Rider.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251221155826_AddRiderAndItsRelatedEntities")]
    partial class AddRiderAndItsRelatedEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CityCab.Rider.API.Models.Rider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(5.0m);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Riders", (string)null);
                });

            modelBuilder.Entity("CityCab.Rider.API.Models.Rider", b =>
                {
                    b.OwnsMany("CityCab.Rider.API.Models.Address", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RiderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id", "RiderId");

                            b1.HasIndex("RiderId");

                            b1.ToTable("RiderAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RiderId");
                        });

                    b.OwnsMany("CityCab.Rider.API.Models.PaymentMethod", "PaymentMethods", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RiderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CardHolderName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CardHolderType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ExpiryMonth")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ExpiryYear")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean");

                            b1.Property<string>("Last4Digits")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ProviderToken")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id", "RiderId");

                            b1.HasIndex("RiderId");

                            b1.ToTable("RiderPaymentMethods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RiderId");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("PaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
